version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
        name: Install Python Dependencies
        command:  |
          pip install --user -r requirements.txt